### ISSUE TITLE
can't sync source code

### ISSUE THREAD

**Issue by chengyi** [nkh-lab/aosp-boost#1]
it reports 
```
repository 'https://git@github.com/boostorg/container_hash/' not found
```

any idea?

**Comment by nkh-lab** [comment]
I've just tested it on my place and it works for both boost-1_66_0.xml and boost-1_72_0.xml manifests. So please rerun repo sync it should work, maybe it was temporary issue with GitHub.

**Comment by chengyi** [comment]
perhaps my aosp verison is different with yours.
