### ISSUE TITLE
Why building libboost_thread using win32 dir src file?

### ISSUE THREAD

**Issue by khailifz** [nkh-lab/aosp-boost#2]
in 1.72.bp file i see this , because you are build at windows pc？
but i see your readme file using linux commad, like ls ln mkdir

`
    exclude_srcs : [
        "thread/src/win32/*.cpp",
        "thread/src/pthread/once_atomic.cpp",
    ],
`

**Comment by nkh-lab** [comment]
Opposite, it excludes the Windows-specific implementation from the build process.

**Comment by khailifz** [comment]
Oh sorry i forget "exclude_srcs" this words .....
